function New-AIForestSummaryReport {
    [CmdletBinding()]
    param(
        [Parameter(ValueFromPipeline = $true)]
        [psobject]
        $ForestSummary,

        [Parameter()]
        [string]
        $OutputPath
    )

    begin {
        $Summaries = @()
    }

    process {
        if ($null -ne $ForestSummary) {
            $Summaries += $ForestSummary
        }
    }

    end {
        if ($Summaries.Count -eq 0) {
            $Summaries = @(Get-AIForestSummary)
        }

        if ([string]::IsNullOrWhiteSpace($OutputPath)) {
            $ModuleRoot = Split-Path $PSScriptRoot -Parent
            $ModulesFolder = Split-Path $ModuleRoot -Parent
            $ProjectRoot = Split-Path $ModulesFolder -Parent
            $ReportFolder = Join-Path $ProjectRoot 'Reports'

            if (-not (Test-Path $ReportFolder)) {
                New-Item -Path $ReportFolder -ItemType Directory -Force | Out-Null
            }

            $Timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
            $OutputPath = Join-Path $ReportFolder "ForestSummary-$Timestamp.html"
        }

        $Rows = foreach ($Summary in $Summaries) {
            [pscustomobject]@{
                CollectedAt = $Summary.CollectedAt
                ForestName = $Summary.ForestName
                RootDomain = $Summary.RootDomain
                ForestMode = $Summary.ForestMode
                SchemaMaster = $Summary.SchemaMaster
                DomainNamingMaster = $Summary.DomainNamingMaster
                DomainCount = @($Summary.Domains).Count
                DomainControllerCount = @($Summary.DomainControllers).Count
                SiteCount = @($Summary.Sites).Count
                GlobalCatalogCount = @($Summary.GlobalCatalogs).Count
                TrustCount = @($Summary.Trusts).Count
            }
        }

        $Style = @'
<style>
body { font-family: Segoe UI, Arial, sans-serif; margin: 32px; color: #1f2933; }
h1 { font-size: 24px; }
table { border-collapse: collapse; width: 100%; margin-top: 16px; }
th, td { border: 1px solid #d0d7de; padding: 8px; text-align: left; }
th { background: #f6f8fa; }
.note { color: #57606a; margin-top: 16px; }
</style>
'@

        $Html = $Rows |
            ConvertTo-Html -Title 'AIInfra Forest Summary' -Head $Style -PreContent '<h1>AIInfra Forest Summary</h1>' -PostContent '<p class="note">Generated by AIInfraWorkbench.</p>'

        $Html | Out-File -FilePath $OutputPath -Encoding UTF8

        Get-Item -Path $OutputPath
    }
}

